apiVersion: v1
kind: Service
metadata:
  name: stellar-service
  namespace: health-watchers
  labels:
    app.kubernetes.io/name: health-watchers
    app.kubernetes.io/component: stellar-service
spec:
  type: ClusterIP
  selector:
    app: stellar-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
