import type { SidebarsConfig } from '@docusaurus/types';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quick-start',
        'getting-started/installation',
        'getting-started/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/monorepo-structure',
        'architecture/service-communication',
        'architecture/data-flow',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/patient-management',
        'features/encounters',
        'features/payments',
        'features/ai-features',
      ],
    },
    {
      type: 'category',
      label: 'Stellar Integration',
      items: [
        'stellar/overview',
        'stellar/payment-flow',
        'stellar/wallet-setup',
        'stellar/testnet-guide',
        'stellar/recurring-billing',
      ],
    },
    {
      type: 'category',
      label: 'Security & Compliance',
      items: [
        'security/authentication',
        'security/rbac',
        'security/hipaa-compliance',
        'security/data-encryption',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/docker',
        'deployment/kubernetes',
        'deployment/environment-variables',
        'deployment/monitoring',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/setup',
        'contributing/coding-standards',
        'contributing/pull-requests',
        'contributing/testing',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
