apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: health-watchers
  labels:
    app.kubernetes.io/name: health-watchers
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api
