{{- if .Values.secrets.useExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: health-watchers-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "health-watchers.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: {{ .Values.secrets.externalSecretRefreshInterval }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecretStore }}
    kind: SecretStore
  target:
    name: health-watchers-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: MONGO_URI
    - secretKey: JWT_ACCESS_TOKEN_SECRET
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: JWT_ACCESS_TOKEN_SECRET
    - secretKey: JWT_REFRESH_TOKEN_SECRET
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: JWT_REFRESH_TOKEN_SECRET
    - secretKey: JWT_SECRET
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: JWT_SECRET
    - secretKey: FIELD_ENCRYPTION_KEY
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: FIELD_ENCRYPTION_KEY
    - secretKey: STELLAR_SECRET_KEY
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: STELLAR_SECRET_KEY
    - secretKey: STELLAR_PUBLIC_KEY
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: STELLAR_PUBLIC_KEY
    - secretKey: STELLAR_PLATFORM_PUBLIC_KEY
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: STELLAR_PLATFORM_PUBLIC_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: GEMINI_API_KEY
    - secretKey: SMTP_USER
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: SMTP_USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: SMTP_PASS
    - secretKey: METRICS_USERNAME
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: METRICS_USERNAME
    - secretKey: METRICS_PASSWORD
      remoteRef:
        key: health-watchers/{{ .Values.global.namespace }}
        property: METRICS_PASSWORD
{{- end }}
