{{- if not .Values.secrets.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: health-watchers-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "health-watchers.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.secrets.jwtAccessTokenSecret | quote }}
  JWT_REFRESH_TOKEN_SECRET: {{ .Values.secrets.jwtRefreshTokenSecret | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  FIELD_ENCRYPTION_KEY: {{ .Values.secrets.fieldEncryptionKey | quote }}
  STELLAR_SECRET_KEY: {{ .Values.secrets.stellarSecretKey | quote }}
  STELLAR_PUBLIC_KEY: {{ .Values.secrets.stellarPublicKey | quote }}
  STELLAR_PLATFORM_PUBLIC_KEY: {{ .Values.secrets.stellarPlatformPublicKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  SMTP_PASS: {{ .Values.secrets.smtpPass | quote }}
  METRICS_USERNAME: {{ .Values.secrets.metricsUsername | quote }}
  METRICS_PASSWORD: {{ .Values.secrets.metricsPassword | quote }}
{{- end }}
